drop table if exists collision;
create table collision (
    accident_index                              text    primary key,
    accident_year                               integer not null,
    accident_reference                          text    not null,
    location_easting_osgr                       integer,
    location_northing_osgr                      integer,
    longitude                                   real,
    latitude                                    real,
    police_force                                integer not null references police_force (id),
    accident_severity                           integer not null references accident_severity (id),
    number_of_vehicles                          integer not null,
    number_of_casualties                        integer not null,
    date                                        text    not null,
    day_of_week                                 integer not null references day_of_week (id),
    time                                        text    not null,
    local_authority_district                    integer not null references local_authority_district (id),
    local_authority_ons_district                text    not null references local_authority_ons_district (id),
    local_authority_highway                     text    not null references local_authority_highway (id),
    first_road_class                            integer not null references first_road_class (id),
    first_road_number                           integer not null,
    road_type                                   integer not null references road_type (id),
    speed_limit                                 integer not null,
    junction_detail                             integer not null references junction_detail (id),
    junction_control                            integer not null references junction_control (id),
    second_road_class                           integer not null references second_road_class (id),
    second_road_number                          integer not null,
    pedestrian_crossing_human_control           integer not null references pedestrian_crossing_human_control (id),
    pedestrian_crossing_physical_facilities     integer not null references pedestrian_crossing_physical_facilities (id),
    light_conditions                            integer not null references light_conditions (id),
    weather_conditions                          integer not null references weather_conditions (id),
    road_surface_conditions                     integer not null references road_surface_conditions (id),
    special_conditions_at_site                  integer not null references special_conditions_at_site (id),
    carriageway_hazards                         integer not null references carriageway_hazards (id),
    urban_or_rural_area                         integer not null references urban_or_rural_area (id),
    did_police_officer_attend_scene_of_accident integer not null references did_police_officer_attend_scene_of_accident (id),
    trunk_road_flag                             integer not null references trunk_road_flag (id),
    lsoa_of_accident_location                   text    not null
);
