name: stats19
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build_stats19:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install prerequisites
              run: 1-install-prerequisites.sh
            - name: Download stats19 metadata and data
              run: 2-download-stats19.sh
            - name: Preprocess data
              run: 3-preprocess.data.sh
            - name: Create tables
              run: 4-create-tables.sh
            - name: Import data
              run: 5-import-data.sh
